[# #]
[*
   $ENV{__EMB_EXTRATITLE}="";
   $ENV{__EMB_SECTION}="Peter's Homepage";

   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {

*]

<H2>Sections</H2>

<p>For now, it's just section 1, that's online.</p>

<ol>
   <li><A href="/script-archive-doc/">Peter's Script-Archive</A> (or <A href="/script-archive/">here</a>)
</ol>

[* } *][# MUST BE AT EOF! #]
