[- qw! "$0" ${1:+"$@"}; exit; reinvoke with embpexec! -]

[*
   # PATH_TRANSLATED - calling name
   $ENV{__EMB_EXTRATITLE}="Overview";
   $ENV{__EMB_FL_URL}="http://github.com/jakobi/script-archive/tree/master";
   $ENV{__EMB_FL_RAW}=$ENV{__EMB_FL_URL}; $ENV{__EMB_FL_RAW}=~s/tree/raw/;
   $ENV{__EMB_FL_DIR}="../REPO.script-archive";

   # invoke master - the the [ * } * ] at EOF
   # (OO base.epl being magic doesn't seem to apply offline)
   # --> we need to set EMBPERL_PATH with all dirs upto root
   #     (or at least the files dir and the 'root')
   # in a single old mail, the author stated the truth:
   # embpexec won't ever work with the embperl object...
   # --> basically offline use is frowned upon.
   #
   # maybe the trick below would work -- but that had also 
   # unsolved bugs back in 2002

   # This once worked for the old HTML::EmbperlObject and might work for the new 
   # use HTML::Embperl::Object;
   # my $path = '/htdocs';
   # my $h = {           path => $path, 
   #           object_addpath => $path, 
   #              object_base => 'base.epl', 
   #                inputfile => "${path}/.index.epl",
   #               outputfile => "${path}/index.html",
   # }; HTML::EmbperlObject::Execute( $h );
   # FIXED WITH A ???
   #              app_name => 'nosuchname',


   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {

*]

<p>A  small archive of UNIX and Linux configuration scraps, notes  and
scripts. The commands are tested with Linux and quite likely were also
used in earlier incarnations on various UNIX versions.</p>






<H2>Notes</H2>



<H3>Philosophy, Ancient Artes and a Modern Tool Chest</H3>

<p><A HREF="motivation.html">Some background on Unix and motivation of
offering this archive.</A></p>



<H3>Suggested Tools &amp; Etymology: The Word Tags Is Derived From TagLS</H3>


<p><A  HREF="suggestion.html">A  selection of the more accessible  and
usable tools from the archive, including TagLS.</A></p>



<H3>Status and Updates</H3>

<p>Status  of the commands checked into this archive: I do  <b>not</b>
use  this archive for development, but rather have a cronjob exporting
the   currently  used  versions  to  the  archive  once  in  a  while.
<b>Bugs</b>:  Given the small size of the commands I do not use a test
harness  setup,  thus  the  pushed version  may  also  contain  recent
breakage  until  the next export. <B>So if you encounter bug, drop  me  a
mail with or without a patch, I'm interested in fixing them or I might
already fixed the problem locally.</B></p>


<H3>Installation Notes</H3>

<p><A  HREF="installation.html">Read  this  for  information  on  e.g.
placement of Perl modules and configuration files.</A></p>


<H3>Licence</H3>

<p>The     scripts    are    made    available    under     the     <a
href="http://github.com/jakobi/script-archive/raw/master/gpl.txt">GPL
v3</a> unless noted otherwise within the script.</p>



<H2>Complete List</H2>

<p><a href="http://github.com/jakobi/script-archive/">The git archive with all files is availble here</a></p>


<p><font  size=large>WARNING - MOST OF THE COMMANDS MENTIONED IN ABOVE
PAGES HAVE NOT YET BEEN IMPORTED INTO GIT - DROP ME A LINE TO ADD SOME
COMMAND EARLY :)</font></p>

[- Execute('gitfilelist.epl'); -]
[* } *][# MUST BE AT EOF! #]
